apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  labels:
    app: elasticsearch
  namespace: logging
spec:
  storageClassName: cbs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
